repos:
-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-added-large-files
    - id: end-of-file-fixer
    - id: check-docstring-first
    - id: debug-statements
    - id: requirements-txt-fixer
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
