#!/usr/bin/env python3
#
# project aquarium's backend
# Copyright (C) 2021 SUSE, LLC.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

import os
import sys
import errno
import json
from typing import Any, Dict, List, Optional, Tuple
import click
import logging
import subprocess
import shlex
import shutil
import random
from click.decorators import make_pass_decorator
from pathlib import Path
from datetime import datetime as dt
from pydantic import BaseModel

logging.basicConfig(level=logging.INFO)
logger: logging.Logger = logging.getLogger("aquarium")


class BaseError(Exception):
    _msg: str

    def __init__(self, msg: str = ""):
        self._msg = msg

    @property
    def message(self) -> str:
        return self._msg


class BoxAlreadyExistsError(BaseError):
    pass


class BuildsPathNotFoundError(BaseError):
    pass


class RootNotFoundError(BaseError):
    pass


class ImageNotFoundError(BaseError):
    pass


class DeploymentPathNotFoundError(BaseError):
    pass


class DeploymentExistsError(BaseError):
    pass


class DeploymentNotFoundError(BaseError):
    pass


class DeploymentNotFinishedError(BaseError):
    pass


class EnterDeploymentError(BaseError):
    pass


class DeploymentStatusError(BaseError):
    pass


class DeploymentModel(BaseModel):
    name: str
    created_on: dt
    box: Optional[str]


class AppCtx:

    _json_output: bool

    def __init__(self, json_output: bool):
        self._json_output = json_output
        pass

    @property
    def json(self) -> bool:
        return self._json_output


pass_appctx = make_pass_decorator(AppCtx)


def _find_root() -> Path:
    cwd = Path.cwd()

    def git_exists(path: Path) -> bool:
        gitpath = path.joinpath(".git")
        return gitpath.exists() and gitpath.is_dir()

    while cwd.as_posix() != "/":
        if git_exists(cwd):
            return cwd
        cwd = cwd.parent

    raise RootNotFoundError()


def _find_builds_path() -> Path:
    try:
        rootdir = _find_root()
    except RootNotFoundError:
        raise BuildsPathNotFoundError("unable to find root")

    builds: Path = rootdir.joinpath("images/build")
    if not builds.exists():
        raise BuildsPathNotFoundError()
    return builds


def _find_deployments_path() -> Path:
    try:
        rootdir = _find_root()
    except RootNotFoundError:
        raise DeploymentPathNotFoundError("unable to find root")

    vagrantdir = rootdir.joinpath("tests/vagrant")
    setupsdir = vagrantdir.joinpath("deployments")
    if not setupsdir:
        raise DeploymentPathNotFoundError("unable to find deployments dir")
    return setupsdir


def _get_deployment_path(name: str) -> Path:
    """ Obtain path to deployment `name` """
    deployments = _list_deployments()
    if name not in deployments:
        raise DeploymentNotFoundError(f"unable to find deployment '{name}'")

    deployments_path = _find_deployments_path()
    assert deployments_path.exists()
    deployment = deployments_path.joinpath(name)
    assert deployment.exists()
    return deployment


@click.group()
@click.option("-d", "--debug", flag_value=True)
@click.option("--json", flag_value=True)
@click.pass_context
def app(ctx: click.Context, debug: bool, json: bool) -> None:

    if debug:
        logger.setLevel(logging.DEBUG)

    logger.debug(f"app => debug: {debug}, ctx: {ctx}")
    ctx.obj = AppCtx(json_output=json)


def _list_boxes() -> List[Tuple[str,str]]:
    """ List all known vagrant boxes. Includes non-aquarium related boxes. """
    proc = subprocess.run(
        shlex.split("vagrant box list --machine-readable"),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )

    stdout = proc.stdout.decode("utf-8")
    stderr = proc.stderr.decode("utf-8")
    if proc.returncode != 0:
        logger.error(f"error running vagrant: {stderr}")

    logger.debug(f"boxes: {stdout}")

    boxes = [name for name in stdout.splitlines() if name.count("box-name") > 0]
    providers = [provider for provider in stdout.splitlines() if provider.count("box-provider") > 0]
    boxlist: List[Tuple[str,str]] = []
    for box_entry, provider_entry in zip(boxes, providers):
        boxname = box_entry.split(",")[3]
        provider = provider_entry.split(",")[3]
        logger.debug(f"boxname: {boxname}, provider: {provider}")
        boxlist.append((boxname, provider))
    return boxlist


def _list_images() -> List[Tuple[str, str]]:
    """ List all built Vagrant images """
    try:
        rootdir = _find_root()
    except RootNotFoundError:
        logger.error("couldn't find git root tree")
        sys.exit(1)

    imagepath = rootdir.joinpath("images")
    buildspath = imagepath.joinpath("build")
    if not buildspath.exists():
        return []

    def is_vagrant_img(path: Path) -> (bool, str):
        assert path.exists()
        outdir = path.joinpath("_out")
        if not outdir.exists():
            raise FileNotFoundError()

        rawimg: Optional[Path] = None
        img: Optional[Path] = None
        provider = None
        for entry in next(os.walk(outdir))[2]:
            if not entry.startswith("project-aquarium"):
                continue

            imgpath = Path(entry)
            if imgpath.suffix == ".raw":
                rawimg = imgpath
            elif imgpath.suffix == ".box":
                if entry.count("vagrant") > 0:
                    img = imgpath
                if entry.count("virtualbox") > 0:
                    provider = "virtualbox"
                elif entry.count("libvirt") > 0:
                    provider = "libvirt"

        if not rawimg:
            raise FileNotFoundError()
        elif not img:
            return False, provider
        return True, provider 

    images: List[Tuple[str,str]] = []
    for build in next(os.walk(buildspath))[1]:
        if build.startswith("."):
            continue
        try:
            ret, provider = is_vagrant_img(buildspath.joinpath(build))
        except FileNotFoundError:
            logger.debug(f"build {build} not a vagrant build")
            continue

        if not ret:
            logger.debug(f"build {build} not a vagrant build")
            continue

        images.append((build, provider))

    return images


def _list_deployments() -> List[str]:
    """ List all existing Aquarium's Vagrant deployments. """
    try:
        rootdir = _find_root()
    except RootNotFoundError:
        logger.error("unable to find git's root dir")
        sys.exit(1)

    vagrantdir = rootdir.joinpath("tests/vagrant")
    setupsdir = vagrantdir.joinpath("deployments")
    if not vagrantdir.exists() or not setupsdir.exists():
        return []

    setups = [entry for entry in next(os.walk(setupsdir))[1]]
    return setups


def _get_deployment_meta(name: str) -> DeploymentModel:
    """ Obtain a given deployment's metadata """
    deployments_path = _find_deployments_path()
    deployment = deployments_path.joinpath(name)
    assert deployment.exists()

    metafile = deployment.joinpath("meta.json")
    if metafile.exists():
        return DeploymentModel.parse_file(metafile)

    created_on_str: str = ""
    createdon_path = deployment.joinpath("created_on")
    if createdon_path.exists():
        created_on_str = createdon_path.read_text()

    return DeploymentModel(
        name=name,
        created_on=created_on_str,
        box=None
    )


def _get_deployments() -> List[DeploymentModel]:
    """ Obtain deployment metadata for all known deployments """
    deployments_lst = _list_deployments()
    deployments: List[DeploymentModel] = []
    for entry in deployments_lst:
        deployments.append(_get_deployment_meta(entry))
    return deployments


def _import_image(imgname: str) -> None:
    """ Import an image as a vagrant box with the same name. """
    avail_boxes = _list_boxes()
    if imgname in [box_name for box_name, _ in avail_boxes]:
        raise BoxAlreadyExistsError()

    try:
        buildspath: Path = _find_builds_path()
    except BuildsPathNotFoundError:
        raise ImageNotFoundError("no available builds")

    imgbuild = buildspath.joinpath(imgname)
    if not imgbuild.exists():
        raise ImageNotFoundError(f"build for image '{imgname}' not found")

    outpath = imgbuild.joinpath("_out")
    if not outpath:
        raise ImageNotFoundError(f"image '{imgname}' not built")

    outfiles = [entry for entry in next(os.walk(outpath))[2]]
    found: Optional[str] = None
    for file in outfiles:
        if file.count(".vagrant.") > 0 and file.endswith(".box"):
            found = file
            break

    if not found:
        raise ImageNotFoundError(f"image '{imgname}' not found at {outpath}")

    imgpath: Path = outpath.joinpath(found)
    assert imgpath.exists()

    boxname = imgname
    cmd = f"vagrant box add {boxname} {imgpath}"
    logger.debug(f"adding box {boxname} from image at {imgpath}")
    proc = subprocess.run(
        shlex.split(cmd),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )

    stderr = proc.stdout.decode("utf-8")
    if proc.returncode != 0:
        raise BaseException(f"error adding vagrant box: {stderr}")


def _remove_box(name: str) -> None:
    """ Remove an existing box """
    boxes = _list_boxes()
    if name not in [box_name for box_name, _ in boxes]:
        return

    cmd = f"vagrant box remove {name}"
    proc = subprocess.run(
        shlex.split(cmd),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )

    if proc.returncode != 0:
        stderr = proc.stderr.decode("utf-8")
        raise BaseError(f"error removing box '{name}': {stderr}")


def _remove(name: str) -> None:
    """ Remove an existing deployment """

    try:
        deployment = _get_deployment_path(name)
    except DeploymentNotFoundError:
        return

    if not deployment.exists():
        return

    shutil.rmtree(deployment)


def _create(
    name: str,
    box: str,
    provider: str,
    num_nodes: int,
    num_disks: int,
    num_nics: int
) -> None:
    """ Create a new deployment, based on provided box. """
    logger.debug(f"_create: Name: {name}, Box: {box}, Provider: {provider}, Nodes\
            : {num_nodes}, Disks: {num_disks}, Nics: {num_nics}")
    rootdir = _find_root()
    assert rootdir.exists()

    deployment_path = _find_deployments_path()
    if not deployment_path.exists():
        deployment_path.mkdir()
    assert deployment_path.exists()

    deployments = _list_deployments()
    boxes = _list_boxes()
    assert name not in deployments
    
    box_exist = False
    for box_name, provider_name in boxes:
        logger.debug(f"_create boxes {box_name} {provider_name}, searching for {box} {provider}")
        if box_name == box and provider_name == provider:
            box_exist = True
    assert box_exist == True
    # assert (box, provider) in boxes

    new_deployment = deployment_path.joinpath(name)
    if new_deployment.exists():
        logger.error(f"deployment {name} already exists")
        raise DeploymentExistsError()

    try:
        logger.debug(f"creating new deployment at '{new_deployment}'")
        new_deployment.mkdir()
    except Exception as e:
        logger.error(
            f"unable to create deployment at {new_deployment}: {str(e)}"
        )
        raise BaseError(f"error creating deployment: {str(e)}")

    logger.debug(
        f"generate template, nodes={num_nodes}, disks={num_disks}, "
        f"nics={num_nics}'"
    )
    vagrantfile_text = _gen_vagrantfile(
        box, provider, rootdir, False,
        num_nodes, num_disks, num_nics
    )

    vagrantfile = new_deployment.joinpath("Vagrantfile")
    logger.debug(f"writing vagrantfile at '{vagrantfile}'")
    vagrantfile.write_text(vagrantfile_text)

    now = dt.now()
    metafile = new_deployment.joinpath("meta.json")
    assert not metafile.exists()
    meta = DeploymentModel(
        name=name,
        created_on=now,
        box=box
    )
    metafile.write_text(meta.json())


def _gen_vagrantfile(
    boxname: str,
    provider: str,
    rootdir: Path,
    without_nfs: bool,
    nodes: int,
    disks: int,
    nics: int
) -> str:

    without_nfs_str: str = "true" if without_nfs else "false"

    create_node_storage: str = ""
    if provider == "virtualbox":
        create_node_storage = \
            f"""
vb_config = `VBoxManage list systemproperties`.split(/\\n/).grep(/Default machine folder/).first
diskpath = vb_config.split(':', 2)[1].strip() """
        for nid in range(1, nodes+1):
            for did in range(1, disks+1):
                create_node_storage += \
                    f"""
N{nid}DISK{did} = File.join(diskpath, '{boxname}-node{nid}', 'node{nid}-disk{did}.vdi') """
    template: str = \
        f"""
# -*- mode: ruby -*-
# vim: set ft=ruby
{create_node_storage}

Vagrant.configure("2") do |config|
    config.vm.box = "{boxname}"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "{rootdir}", "/srv/aquarium", type: "nfs", nfs_udp: false, disabled: {without_nfs_str}
    config.vm.guest = "suse"
        """

    host_port = 1337
    for nid in range(1, nodes+1):

        node_networks: str = ""
        for _ in range(0, nics-1):
            node_networks += \
                """
        node.vm.network :private_network, :type => "dhcp" """

        node_storage: str = ""
        if provider == "virtualbox":
            node_storage += \
                f"""
            lv.customize ['storagectl', :id, '--name', 'SATA Controller', '--portcount', '6'] """
        for did in range(1, disks+1):
            if provider == "libvirt":
                serial = "".join(random.choice("0123456789") for _ in range(8))
                node_storage += \
                    f"""
            lv.storage :file, size: "8G", type: "qcow2", serial: "{serial}" """
            elif provider == "virtualbox":
                node_storage += \
                    f"""
            unless File.exist?(N{nid}DISK{did})
                lv.customize ['createhd', '--filename', N{nid}DISK{did}, '--format', 'VDI', '--size', '20000' ]
            end
            lv.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', {did}, '--device', 0, '--type', 'hdd', '--medium', N{nid}DISK{did}] """

        is_primary_str = "true" if nid == 1 else "false"
        node_str: str = \
            f"""
    config.vm.define :"node{nid}", primary: {is_primary_str} do |node|
        node.vm.hostname = "node{nid}"
        node.vm.network "forwarded_port", guest: 1337, host: {host_port}, host_ip: "*"
        {node_networks}
        node.vm.provider "{provider}" do |lv|
            lv.memory = 4096
            lv.cpus = 1
            {node_storage}
        end
    end
            """

        template += node_str
        host_port += 1

    template += \
        """
end
        """

    return template


#
# create and remove setups
#
@app.command("create")
@click.option("-b", "--box", type=str, required=False)
@click.option("-i", "--image", type=str, required=False)
@click.option("-f", "--force", flag_value=True)
@click.option("--num-nodes", required=False, type=int)
@click.option("--num-disks", required=False, type=int)
@click.option("--num-nics", required=False, type=int)
@click.argument("name", required=True, type=str)
@pass_appctx
def cmd_create(
    ctx: AppCtx,
    name: str,
    box: Optional[str],
    image: Optional[str],
    force: bool,
    num_nodes: Optional[int],
    num_disks: Optional[int],
    num_nics: Optional[int]
) -> None:
    """
    Create a new deployment
    """
    logger.debug(f"create: ctx = {ctx}, name: {name}, box: {box}, img: {image}")

    num_disks = num_disks if num_disks is not None else 4
    num_nics = num_nics if num_nics is not None else 1
    num_nodes = num_nodes if num_nodes is not None else 2

    avail_images = _list_images()
    avail_boxes = _list_boxes()
    avail_deployments = _list_deployments()

    remove_existing_deployment = False
    provider = ""

    if name in avail_deployments:
        if not force:
            click.secho(f"Deployment '{name}' already exists", fg="red")
            sys.exit(errno.EEXIST)
        remove_existing_deployment = True

    if box and image:
        click.secho("Please provide only one of '--box' or '--image'", fg="red")
        sys.exit(errno.EINVAL)

    """
    User did not assign box or image
    1) search for existing default aquarium box and provider type, then flag it
    2) look up available image name and provider type, then flag it 
    3) if nither exist , error out
    """
    if not box and not image:
        click.secho(f"Using default 'aquarium' as box name and image name", fg="green")
        aquarium_box_exist = False
        aquarium_image_exist = False
        for box_name, provider_name in avail_boxes:
            if box_name == "aquarium" or box_name == name:
                aquarium_box_exist = True
                box = box_name
                provider = provider_name
        for img_name, provider_name in avail_images:
            if aquarium_box_exist:
                if img_name == box and provider_name == provider:
                    aquarium_image_exist = True
            elif img_name == "aquarium" or img_name == name:
                aquarium_image_exist = True
                image = img_name
                provider = provider_name

        if aquarium_box_exist:
            click.secho(f"Box '{box}' exist with Provider '{provider}' is availble", fg="green")
        elif aquarium_image_exist:
            click.secho(f"Image '{image}' exist with Provider '{provider}' is availble", fg="green")
        else:
            click.secho("Unable to find default box or default image 'aquarium'", fg="red")
            sys.exit(errno.ENOENT)

    """
    Either User assign the image name or we get it from listing existing image
    1) check if user assign image still exist 
    2) if image name is box name with force flag, remove the box  
    3) create box with image name, if image already in box list with no force flag, reuse 
    """
    if not box and image:
        click.secho(f"Using image '{image}' to create box and deployment", fg="green")
        if image not in [image_name for image_name, _ in avail_images]:
            click.secho(f"Image '{image}' not found", fg="red")
            sys.exit(errno.ENOENT)

        if image in [image_name for image_name, _ in avail_boxes] and force:
            # remove existing box first
            try:
                _remove_box(image)
            except BaseError as e:
                logger.error(
                    f"Unable to remove existing box '{image}': {e.message}"
                )
                sys.exit(1)
        try:
            click.secho(f"Importing image '{image}' as Vagrant box", fg="cyan")
            _import_image(image)
            avail_boxes = _list_boxes()
        except ImageNotFoundError as e:
            click.secho(f"Error importing image '{image}': {e.message}")
            sys.exit(1)
        except BoxAlreadyExistsError:
            click.secho("Box already exists, reusing.", fg="green")
            box = image
        for image_name, provider_name in avail_boxes:
            if image_name == image:
                box = image
                provider = provider_name
        click.secho(f"Imported image: '{box}' as Vagrant box Provider: {provider}", fg="green")

    assert box is not None
    box_exist = False
    for box_name, provider_name in avail_boxes:
        if box_name == box:
            provider = provider_name
            box_exist = True
    if box_exist:
        click.secho(f"Using box '{box}' provider '{provider}'", fg="green")
    else:
        click.secho(f"Unable to find box '{box}'", fg="red")
        return

    if remove_existing_deployment:
        click.secho(f"Removing existing deployment '{name}'")
        try:
            _remove(name)
        except BaseError as e:
            logger.error(f"error removing deployment '{name}': {e.message}")
        click.secho(f"Removed deployment '{name}'")

    try:
        _create(name, box, provider, num_nodes, num_disks, num_nics)
    except Exception as e:
        click.secho(
            f"Error creating deployment '{name}' from box '{box}': {str(e)}",
            fg="red"
        )
        raise e
    click.secho("success!", fg="green")


@app.command("remove")
@click.argument("name", required=True, type=str)
@pass_appctx
def cmd_remove(ctx: AppCtx, name: str) -> None:
    """
    Remove a deployment; doesn't remove the deployment's box
    """
    logger.debug(f"remove => name: {name}, ctx: {ctx}")

    must_stop: bool = False
    state: List[Tuple[str, str]] = _get_deployment_state(name)
    for node, node_state in state:
        if node_state == "running":
            click.secho(f"node '{node}' is still running", fg="red")
            must_stop = True
    if must_stop:
        click.secho("Please stop the deployment before removing", fg="yellow")
        sys.exit(errno.EBUSY)

    click.secho(f"Removing deployment '{name}'", fg="cyan")
    _remove(name)
    click.secho("Removed.", fg="green")


def print_entry(name: str) -> None:
    """ Print an entry in the format '* NAME', with pretty colors """
    print("{} {}".format(
        click.style("*", fg="cyan"),
        click.style(name, fg="white", bold=True)
    ))


def print_json(what: Any) -> None:
    print(json.dumps(what))


def _parse_vagrant(raw: str) -> Dict[str, List[Tuple[str, str]]]:

    result: Dict[str, List[Tuple[str, str]]] = {}
    lines = raw.splitlines()

    for line in lines:
        fields = line.split(",")
        entry: Tuple[str, str] = (fields[1], fields[3])
        state: str = fields[2]
        if state not in result:
            result[state] = []
        result[state].append(entry)

    return result


def _get_deployment_status(name: str) -> Dict[str, List[Tuple[str, str]]]:
    """
    Returns a List of Tuples with the node's name as first element, and the
    node's state as the second element.
    """

    path: Path = _get_deployment_path(name)
    if not path.exists():
        raise DeploymentPathNotFoundError()

    vagrantfile = path.joinpath("Vagrantfile")
    if not vagrantfile:
        raise DeploymentNotFinishedError()

    env: Dict[str, str] = os.environ.copy()
    env["VAGRANT_CWD"] = str(path)
    proc = subprocess.run(
        shlex.split("vagrant status --machine-readable"),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=env
    )

    if proc.returncode != 0:
        stderr = proc.stderr.decode("utf-8")
        raise DeploymentStatusError(stderr)

    return _parse_vagrant(proc.stdout.decode("utf-8"))


def _get_deployment_state(name: str) -> List[Tuple[str, str]]:

    try:
        metadata: Dict[str, List[Tuple[str, str]]] = \
            _get_deployment_status(name)
    except BaseError as e:
        logger.error(f"unable to obtain deployment's state: {str(e)}")
        raise e

    if "state" not in metadata:
        return []

    return metadata["state"]


def _check_deployment_state(name: str, statenames: List[str]) -> bool:

    try:
        state: List[Tuple[str, str]] = _get_deployment_state(name)
    except BaseError as e:
        logger.error(f"unable to check deployment's state: {str(e)}")
        raise e

    num_at_state: int = 0
    num_nodes: int = 0

    for _, node_state in state:
        num_nodes += 1
        if node_state in statenames:
            num_at_state += 1

    assert num_nodes > 0
    return num_at_state > 0


#
# start, stop, shell commands
#

def _vagrant_enter_deployment(name: str) -> None:

    # may raise DeploymentNotFound
    deployment = _get_deployment_path(name)

    try:
        os.chdir(deployment)
    except Exception as e:
        logger.error(f"unable to change directories: {str(e)}")
        raise EnterDeploymentError(str(e))

    vagrantfile = deployment.joinpath("Vagrantfile")
    if not vagrantfile.exists():
        logger.error(f"unable to find Vagrantfile at {vagrantfile}")
        raise DeploymentNotFinishedError()


def _cmd_try_vagrant_deployment(name: str) -> None:

    error: int = 0
    try:
        _vagrant_enter_deployment(name)
    except DeploymentNotFoundError:
        click.secho(f"Deployment '{name}' not found", fg="red")
        error = errno.ENOENT
    except DeploymentNotFinishedError:
        click.secho(f"Deployment '{name}' wasn't finished. Should recreate.")
        error = errno.EINVAL
    except FileNotFoundError:
        click.secho("Couldn't find Deployment's directory")
        error = errno.ENOENT
    except PermissionError:
        click.secho(f"No permissions to use Deployment '{name}'")
        error = errno.EPERM

    if error != 0:
        sys.exit(error)


@app.command("start")
@click.argument("name", required=True, type=str)
@click.option("--conservative", flag_value=True)
@pass_appctx
def cmd_start(ctx: AppCtx, name: str, conservative: bool) -> None:
    """
    Start a deployment
    """
    _cmd_try_vagrant_deployment(name)

    try:
        running: bool = _check_deployment_state(name, ["running", "preparing"])
    except BaseError as e:
        click.secho(f"Something went wrong: {e.message}", fg="red")
        sys.exit(errno.EINVAL)

    if running:
        click.secho("Deployment already running", fg="yellow")
        return

    cmd = "vagrant up"
    if conservative:
        cmd += " --no-parallel --no-destroy-on-error"

    proc = subprocess.run(
        shlex.split(cmd),
        stderr=subprocess.PIPE
    )

    if proc.returncode != 0:
        stderr = proc.stderr.decode("utf-8")
        logger.error(f"unable to start vagrant machines: {stderr}")
        click.secho("Unable to start deployment", fg="red")
        sys.exit(1)

    click.secho("Deployment started.")


@app.command("stop")
@click.argument("name", required=True, type=str)
@pass_appctx
def cmd_stop(ctx: AppCtx, name: str) -> None:
    """
    Stop deployment; destroys running machines
    """

    _cmd_try_vagrant_deployment(name)

    try:
        stopped: bool = \
            _check_deployment_state(name, ["shutoff", "not_created"])
    except BaseError as e:
        click.secho(f"Something went wrong: {e.message}", fg="red")
        sys.exit(errno.EINVAL)

    if stopped:
        click.secho("Deployment already stopped.", fg="green")
        return

    proc = subprocess.run(
        shlex.split("vagrant destroy"),
        stderr=subprocess.PIPE
    )

    if proc.returncode != 0:
        stderr = proc.stderr.decode("utf-8")
        logger.error(f"Unable to stop vagrant machines: {stderr}")
        click.secho("Unable to stop deployment", fg="red")
        sys.exit(1)

    click.secho("Deployment stopped.", fg="green")


@app.command("shell")
@click.argument("name", required=True, type=str)
@click.option("-n", "--node", required=False, type=str)
@pass_appctx
def cmd_shell(ctx: AppCtx, name: str, node: str) -> None:
    """
    Obtain a shell for a deployment; can specify node
    """

    _cmd_try_vagrant_deployment(name)

    running = False
    try:
        running: bool = _check_deployment_state(name, ["running"])
    except BaseError as e:
        click.secho(f"Something went wrong: {e.message}", fg="red")

    if not running:
        click.secho("Deployment not running.", fg="yellow")
        sys.exit(1)

    if node:
        has_node: bool = False
        metadata: Dict[str, List[Tuple[str, str]]] = \
            _get_deployment_status(name)
        for nodename, state in metadata["state"]:
            if nodename == node:
                if state != "running":
                    click.secho(f"Node '{node}' not running", fg="red")
                    sys.exit(errno.EINVAL)
                has_node = True
            if has_node:
                break
        if not has_node:
            click.secho(f"Deployment node '{node}' does not exist", fg="red")
            sys.exit(errno.ENOENT)

    cmd = "vagrant ssh"
    if node:
        cmd += f" {node}"

    subprocess.run(shlex.split(cmd))


@app.command("status")
@click.argument("name", required=False, type=str)
@pass_appctx
def cmd_status(ctx: AppCtx, name: Optional[str]) -> None:
    """
    Obtain status of existing deployments
    """

    deployments: List[str] = _list_deployments()

    if name:
        if name not in deployments:
            click.secho(f"Unknown deployment '{name}'", fg="red")
            sys.exit(errno.ENOENT)
        deployments = [name]

    for deployment in deployments:
        hdr = chr(0x25CF)
        click.secho("{} {}".format(
            click.style(hdr, fg="cyan", bold=True),
            click.style(f"{deployment}", fg="white", bold=True)
        ))
        state = _get_deployment_state(deployment)

        while len(state) > 0:
            entry: Tuple[str, str] = state.pop(0)
            boxline = chr(0x251C)
            if len(state) == 0:
                boxline = chr(0x2514)

            node, node_state = entry
            color: str = "green" if node_state == "running" else "red"
            node_state = " ".join(node_state.split("_"))
            click.secho("{} {} {}".format(
                click.style(boxline, fg="cyan", bold=True),
                click.style(f"{node}:", fg="white"),
                click.style(node_state, fg=color)
            ))


@app.command("list")
@click.option("-v", "--verbose", flag_value=True)
@pass_appctx
def cmd_list(ctx: AppCtx, verbose: bool) -> None:
    """
    List existing deployments
    """
    logger.debug("list deployments")
    deployments: List[DeploymentModel] = _get_deployments()
    if len(deployments) == 0:
        click.secho("No deployments found", fg="cyan")
        return

    json_lst: List[Dict[str, Any]] = []
    for deployment in deployments:

        if ctx.json:
            json_lst.append(
                json.loads(deployment.json())
            )
            continue

        header = chr(0x25cf)
        click.secho("{} {}".format(
            click.style(header, fg="cyan", bold=True),
            click.style(f"{deployment.name}", fg="white", bold=True)
        ))

        def _print(prefix: str, what: str, value: str) -> None:
            click.secho("{} {}: {}".format(
                click.style(prefix, fg="cyan", bold=True),
                click.style(what, fg="white", bold=True),
                click.style(value, fg="white")
            ))

        if verbose:
            treeline = chr(0x251c)
            treeend = chr(0x2514)

            boxname = deployment.box if deployment.box else "unknown"
            _print(treeline, "created on", str(deployment.created_on))
            _print(treeend, "box", boxname)

    if ctx.json:
        print(json.dumps(json_lst))


#
# box-related commands
#
@app.group("box")
def cmd_box() -> None:
    """
    Box related commands
    """
    logger.debug("box")
    pass


@cmd_box.command("list")
@click.option("-v", "--verbose", flag_value=True)
@pass_appctx
def cmd_box_list(ctx: AppCtx, verbose: bool) -> None:
    logger.debug("list boxes")
    boxes = _list_boxes()
    deployments = _get_deployments()
    deployment_per_box: Dict[str, List[DeploymentModel]] = {}

    for deployment in deployments:
        box = deployment.box
        if box and box in boxes:
            if box not in deployment_per_box:
                deployment_per_box[box] = []
            deployment_per_box[box].append(deployment)

    if len(boxes) == 0:
        click.secho("No boxes found", fg="cyan")
        return

    if ctx.json:
        print_json(boxes)
        return

    headerchr = chr(0x25cf)
    for boxname, provider in boxes:
        num_deployments = 0 if boxname not in deployment_per_box \
                            else len(deployment_per_box[boxname])
        click.secho("{} {} ({} deployments) [provider {}]".format(
            click.style(headerchr, fg="cyan", bold=True),
            click.style(boxname, fg="white", bold=True),
            num_deployments,
            click.style(provider, fg="white", bold=True)
        ))

        if verbose and num_deployments > 0:
            lst = deployment_per_box[boxname]
            while len(lst) > 0:
                dep = lst.pop(0)
                prefix = chr(0x251c) if len(lst) > 0 else chr(0x2514)
                click.secho("{} {}".format(
                    click.style(prefix, fg="cyan", bold=True),
                    click.style(dep.name, fg="white")
                ))


#
# image related commands
#
@app.group("image")
def cmd_images() -> None:
    """
    Image related commands
    """
    logger.debug("image")
    pass


@cmd_images.command("list")
@pass_appctx
def cmd_images_list(ctx: AppCtx) -> None:
    logger.debug("list images")
    images = _list_images()
    if len(images) == 0:
        click.secho("No images found", fg="cyan")
        return

    if ctx.json:
        print_json(images)
        return

    for image, provider in images:
        print_entry(f"{image} ({provider})")
        # print(f"Provider: {provider}")


if __name__ == "__main__":
    app()
