[tool.black]
line-length = 80
target-version = ['py38']
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
# As this is `extend`, we already exclude everything in .gitignore.
^/(
  (
      glass                    # don't bother looking through glass
    | gravel/ceph.git          # don't try formatting ceph.git
  )/
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 80
extend_skip_glob = ["glass/*", "gravel/ceph.git/*"]
