name: "Glass unit tests"

on:
  - push
  - pull_request

jobs:
  nodejs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: src/glass
      - run: npx ng build
        working-directory: src/glass
      - run: npm run test:ci
        working-directory: src/glass
